# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - referenceplus

on:
  push:
    branches:
      - main
  workflow_dispatch:

   # set GH repo secret with the publish profile of the web app

env:
      AZURE_WEBAPP_NAME: referenceplus  # set this to your application's name
      AZURE_WEBAPP_PACKAGE_PATH: ${{ github.workspace }} # set this to the path to your web app project
      JAVA_VERSION: '18'                # set this to the Java version to use
      AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_53D966A5B15F4D7CA7A3DE29E656F6B2 }}  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '18'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: path/to/artifact
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
     - uses: actions/download-artifact@v3
       with:
        path: path/to/artifact
        
     - name: Deploy to Azure Web App
       id: deploy-to-webapp
       uses: azure/webapps-deploy@v2
       with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
    	    publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
		      package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/target/*.jar'
